'use client';

import { Itinerary } from '@/lib/types';
import StopCard from './StopCard';

type Props = {
  itinerary: Itinerary;
  highlightedStop: string | null;
  onHighlight: (id: string) => void;
};

export default function ItineraryView({ itinerary, highlightedStop, onHighlight }: Props) {
  return (
    <div className="h-full overflow-y-auto px-6 py-8">
      <div className="max-w-xl mx-auto">
        <div className="mb-8">
          <p className="text-xs font-medium uppercase tracking-widest text-forest mb-2">
            {itinerary.neighborhood}{itinerary.secondNeighborhood ? ` → ${itinerary.secondNeighborhood}` : ''} · {itinerary.city}
          </p>
          <h1 className="font-display text-3xl font-bold text-slate-900 leading-tight mb-4">
            {itinerary.title}
          </h1>
          <p className="font-display text-base text-slate-600 leading-relaxed">
            {itinerary.intro}
          </p>
          <p className="mt-3 text-sm text-slate-400">{itinerary.stops.length} stops · full day</p>
        </div>

        <div className="flex flex-col gap-5">
          {itinerary.stops.map((stop, i) => (
            <StopCard
              key={stop.id}
              stop={stop}
              index={i}
              isHighlighted={highlightedStop === stop.id}
              onHighlight={onHighlight}
            />
          ))}
        </div>

        <p className="mt-10 text-center text-xs text-slate-300">
          Generated by Localish &middot; Your local friend&apos;s guide
        </p>
      </div>
    </div>
  );
}
